# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

#r_packages:
#  - covr

#after_success:
#  - travis_wait 40
#  - Rscript -e 'library(covr); codecov()'
