# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

r_github_packages:
   - jimhester/robustr
   - jimhester/covr

after_success:
  - Rscript -e 'library(covr); codecov()'
