# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - devel
  - release
sudo: required
cache: false

r_packages:
  - devtools
  - withr
  - covr
  - curl

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'
